/**
 * Remark plugin: wrap markdown `<img>` references to `/public` assets in a
 * `<picture>` that serves the WebP companion (generated by
 * `scripts/optimize-public-images.mjs`) when the browser supports it.
 *
 * For an image like `![alt](/hackintosh/foo.jpg)`:
 *   <picture>
 *     <source srcset="/hackintosh/foo.webp" type="image/webp">
 *     <img src="/hackintosh/foo.jpg" alt="alt" loading="lazy" decoding="async">
 *   </picture>
 *
 * Falls back to a plain `<img>` (with lazy/async) when no `.webp` sibling exists.
 * Images that aren't under `/` (e.g. external URLs) are left untouched.
 */
import { existsSync } from 'node:fs';
import { join } from 'node:path';
import { visit } from 'unist-util-visit';
import type { Root, Image, Html } from 'mdast';
import type { Plugin } from 'unified';

const RASTER_RE = /\.(jpe?g|png)$/i;

const escapeAttr = (value: string): string =>
  value.replace(/&/g, '&amp;').replace(/"/g, '&quot;').replace(/</g, '&lt;');

const remarkPublicImages: Plugin<[], Root> = () => {
  const publicDir = join(process.cwd(), 'public');

  return (tree) => {
    visit(tree, 'image', (node: Image, index, parent) => {
      if (!parent || typeof index !== 'number') return;
      const url = node.url;
      if (!url.startsWith('/')) return;
      if (!RASTER_RE.test(url)) return;

      const webpUrl = url.replace(RASTER_RE, '.webp');
      const webpExists = existsSync(join(publicDir, webpUrl));
      const alt = node.alt ?? '';
      const title = node.title ? ` title="${escapeAttr(node.title)}"` : '';
      const imgTag =
        `<img src="${escapeAttr(url)}" alt="${escapeAttr(alt)}" ` +
        `loading="lazy" decoding="async"${title}>`;

      const html: Html = {
        type: 'html',
        value: webpExists
          ? `<picture><source srcset="${escapeAttr(webpUrl)}" type="image/webp">${imgTag}</picture>`
          : imgTag,
      };

      parent.children.splice(index, 1, html);
    });
  };
};

export default remarkPublicImages;
